name = "lean-sdl-test"
version = "0.1.0"
defaultTargets = ["lean-sdl-test"]

[[lean_lib]]
name = "LeanSdlTest"

[[require]]
name = "SDL3"
git = "https://github.com/ValorZard/lean-sdl3.git"
rev = "master"

[[lean_exe]]
name = "lean-sdl-test"
root = "Main"
